### ISSUE TITLE
Змінити тип даних в адмінці джанго

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_api#14]
Було б зручно обирати з списку значення для поля `approval` а не вводити їх вручну.
Це ж саме стосується поля 'Time to fish'

**Comment by devrivne** [comment]
це зроблю. Там лише треба добавити тюпла.
permit_choices  = (
('free','free'),
('paid','paid'),
('prohibited','prohibited'),
('unknown', 'unknown')
)
permit = models.CharField(max_length=30, choices=permit_choices, default='free')

**Comment by devrivne** [comment]
для тайм ту фіш так само ('24h', 'daylight', 'unknown')

**Comment by devrivne** [comment]
Resolved.

**Comment by stal1n274** [comment]
Для полів 'Time to fish' і 'Permit' все запрацювало, спасибі

Лишилось 'Approval'

**Comment by devrivne** [comment]
для нього не добавляв) зараз зроблю
