### ISSUE TITLE
API: Додати метод який повертає час останнього редагування маркерів

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_api#3]
Потрібен для реалізації кешу списку маркерів на моб. клієнті.
Можна одразу в UTC.

**Comment by devrivne** [comment]
Маркерів чи маркеру одного якогось? Чи час з моменту редагування любого з маркерів?

**Comment by lordmegamax** [comment]
Будь які зміни в маркерах чи то додали новий чи змінили текст в існуючому
повинні змінити дату редагування.
Це одна глобальна дата.
06 марта 2015 г. 0:33 пользователь "devrivne" <notifications@github.com>
написал:

**Comment by stal1n274** [comment]
У нас є поле в табличці `markers`, яка автоматично ставить поточну дату при будь-якій зміні запису:

```   `modify_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP```

Тобто `markers.modify_date` і є часом останнього редагування маркеру

**Comment by stal1n274** [comment]
ось так можна вибрати цю одну глобальну дату завжди:

```
SELECT
	modify_date
FROM
	markers
ORDER BY 
	modify_date DESC
LIMIT 1
```

**Comment by devrivne** [comment]
Це робиться в межах джанго моделей. Добавлю.

**Comment by lordmegamax** [comment]
нехай буде /lastchanges який повертає час в мілісекундах

**Comment by ttp** [comment]
це буде працювати некоректно, для кешу потрібно використовувати комбінацію count(*) + max(modify_date)

**Comment by stal1n274** [comment]
А навіщо до часу останньої правки в базі даних додавати ще й кількість маркерів?

**Comment by devrivne** [comment]
Скажіть будь-ласка, що мені вертати?
count(*) + max(modify_date)   ????

**Comment by stal1n274** [comment]
> Скажіть будь-ласка, що мені вертати?
> count(*) + max(modify_date) ????

так точно

**Comment by lordmegamax** [comment]
І що воно верне? Unix time в мілісекундах? І що робити з count? Чи count буде окремим параметром?

**Comment by stal1n274** [comment]
API буде повертати просто кеш з набору цифр.
Це юнікс тайм в мілісекундах + кількість маркерів в базі даних

Навіщо додавати оту кількість записів з бази? Це на випадок, якщо якийсь запис просто витерти з таблички, щоб кеш також змінився.

**Comment by lordmegamax** [comment]
Я розумію для чого кількість. Я не про те.

Можна перевіряти на відповідність хешу і завантажувати все заново. Але я думав зробити спочатку просту перевірку по часу останнього редагування, а згодом додати в АРІ метод на зразок "дай всі маркери які змінились після дд.мм.ррр..." - так ефективніше буде використовуватись моб. інтернет і аплікуха буде швидше синхронізуватись.

Але якщо мій варіант вам не цікавить - робіть хеш.

**Comment by stal1n274** [comment]
це число буде відрізнятись від твого на 400 мілісекунд (кількість записів в таблиці). Це ж не суттєва різниця в часі, тому пропоную використовувати його у всіх розрахунках :)

**Comment by lordmegamax** [comment]
Добре, будем думать що всі з 3G. :) 
Тоді очікую метода з хешем.

**Comment by devrivne** [comment]
GET /lastchanges/
HTTP 200 OK
Content-Type: application/json
Vary: Accept
Allow: GET, HEAD, OPTIONS

{
    "lastchanges": 20150324234817.0
}

**Comment by stal1n274** [comment]
> Добре, будем думать що всі з 3G. :) 
> Тоді очікую метода з хешем.

Макс, ну чому не розглядати це число як звичайний timestamp?

**Comment by lordmegamax** [comment]
Це можна зробити цілочисельним типом, в мілісекундах чи хеш про який ми говорили? Або строкою бо в Java починаються нюанси з округленням чисел...

**Comment by stal1n274** [comment]
Потрібно повертати значення цілочисельним типом

**Comment by ttp** [comment]
це має бути стрічка, яке ще цілочисельне?

**Comment by lordmegamax** [comment]
Без різниці, головне щоб не з плаваючою точкою.
